import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Route, Routes, useParams } from 'react-router-dom'
import { getComponent, getConnects, getOverview } from './api'
import type { Component, Connect, Overview } from './types'
import './styles.css'

const ago = (value: string) => { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 30) return '刚刚'; if (seconds < 3600) return `${Math.floor(seconds / 60)} 分钟前`; return new Date(value).toLocaleString() }
const Status = ({ value }: { value: string }) => <span className={`status ${value}`}><i />{value === 'online' ? '在线' : '离线'}</span>
const Header = ({ updated, refresh, loading }: { updated?: string; refresh: () => void; loading: boolean }) => <header><div className="brand-lockup"><img className="brand-mark" src="/brand/mcphub-mark.png" alt="MCPHub logo" /><div><div className="brand">MCPHub</div><div className="subtitle">MCP 管理中心</div></div></div><div className="header-actions"><span className="dev">开发模式</span><span className="muted">{updated ? `更新于 ${ago(updated)}` : '等待数据'}</span><button onClick={refresh} disabled={loading}>{loading ? '刷新中…' : '刷新'}</button></div></header>
const Cards = ({ overview }: { overview?: Overview }) => <section className="cards">{[['连接实例', overview?.connect_total ?? 0, `${overview?.connect_online ?? 0} 在线`], ['在线连接', overview?.connect_online ?? 0, '当前已连接'], ['MCP 服务', overview?.component_total ?? 0, `${overview?.component_online ?? 0} 在线`], ['离线服务', overview?.component_offline ?? 0, '需要检查连接']].map(([label, value, hint]) => <div className="card" key={String(label)}><div className="muted">{label}</div><strong>{value}</strong><small>{hint}</small></div>)}</section>
const ComponentTable = ({ components }: { components: Component[] }) => <div className="table-wrap"><table><thead><tr><th>服务名称</th><th>所属连接</th><th>Transport</th><th>状态</th><th>最后心跳</th><th>MCP 地址</th><th>操作</th></tr></thead><tbody>{components.map(c => <tr key={`${c.connect_id}:${c.id}`}><td><b>{c.name}</b>{c.last_error && <div className="error-text">{c.last_error}</div>}</td><td>{c.connect_id}</td><td><span className="transport">{c.transport}</span></td><td><Status value={c.status} /></td><td title={new Date(c.last_heartbeat).toLocaleString()}>{ago(c.last_heartbeat)}</td><td><code>{c.public_url}</code></td><td><Link className="link" to={`/admin/components/${encodeURIComponent(c.id)}`}>详情</Link><button className="copy" onClick={() => navigator.clipboard?.writeText(c.public_url)}>复制</button></td></tr>)}</tbody></table>{components.length === 0 && <div className="empty">暂无注册的 MCP 服务</div>}</div>
const Dashboard = () => { const [overview, setOverview] = useState<Overview>(); const [connects, setConnects] = useState<Connect[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const refresh = useCallback(async () => { const controller = new AbortController(); setLoading(true); try { const [o, c] = await Promise.all([getOverview(controller.signal), getConnects(controller.signal)]); setOverview(o); setConnects(c); setError('') } catch (e) { if ((e as Error).name !== 'AbortError') setError((e as Error).message) } finally { setLoading(false) } }, []); useEffect(() => { void refresh(); let delay = 5000; let timer: number; const tick = () => { if (document.visibilityState === 'visible') void refresh(); timer = window.setTimeout(tick, delay) }; timer = window.setTimeout(tick, delay); const visible = () => { if (document.visibilityState === 'visible') void refresh() }; document.addEventListener('visibilitychange', visible); return () => { window.clearTimeout(timer); document.removeEventListener('visibilitychange', visible) } }, [refresh]); const components = useMemo(() => connects.flatMap(c => c.components), [connects]); return <><Header updated={overview?.last_updated} refresh={refresh} loading={loading} />{error && <div className="alert">状态 API 暂时不可用：{error}</div>}<main><Cards overview={overview} /><section className="section"><div className="section-title"><div><h2>连接实例</h2><p>按 mcp-connect 实例查看已注册的 MCP 服务</p></div></div>{connects.map(c => <div className="connect-card" key={c.id}><div className="connect-head"><div><h3>{c.name}</h3><span className="muted">{c.id} · {c.version || '未知版本'} · {c.remote_addr || '本地连接'}</span></div><Status value={c.status} /></div><div className="connect-meta"><span>连接于 {new Date(c.connected_at).toLocaleString()}</span><span>最后心跳 {ago(c.last_heartbeat)}</span><span>{c.components.length} 个服务</span></div></div>)}</section><section className="section"><div className="section-title"><div><h2>MCP 服务</h2><p>统一查看可访问地址和连接状态</p></div></div><ComponentTable components={components} /></section></main></> }
const Detail = () => { const { id = '' } = useParams(); const [component, setComponent] = useState<Component>(); const [error, setError] = useState(''); useEffect(() => { const c = new AbortController(); getComponent(decodeURIComponent(id), c.signal).then(setComponent).catch(e => setError(e.message)); return () => c.abort() }, [id]); if (error) return <><Header updated={undefined} refresh={() => undefined} loading={false} /><main><div className="alert">无法加载服务：{error}</div></main></>; if (!component) return <><Header updated={undefined} refresh={() => undefined} loading={false} /><main><div className="empty">加载中…</div></main></>; return <><Header updated={component.last_heartbeat} refresh={() => window.location.reload()} loading={false} /><main><Link className="back" to="/admin">← 返回服务列表</Link><section className="detail"><div className="detail-head"><div><h1>{component.name}</h1><span className="muted">{component.id}</span></div><Status value={component.status} /></div><dl><dt>所属连接</dt><dd>{component.connect_id}</dd><dt>传输类型</dt><dd>{component.transport}</dd><dt>上游地址</dt><dd>{component.upstream_url || '未提供'}</dd><dt>公网 MCP 地址</dt><dd><code>{component.public_url}</code> <button className="copy" onClick={() => navigator.clipboard?.writeText(component.public_url)}>复制</button></dd><dt>注册时间</dt><dd>{new Date(component.registered_at).toLocaleString()}</dd><dt>最后心跳</dt><dd>{new Date(component.last_heartbeat).toLocaleString()}</dd>{component.last_error && <><dt>最近错误</dt><dd className="error-text">{component.last_error}</dd></>}</dl></section></main></> }
const App = () => <Routes><Route path="/admin" element={<Dashboard />} /><Route path="/admin/components/:id" element={<Detail />} /><Route path="*" element={<Dashboard />} /></Routes>
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>)
